version: "3.9"

services:

  db:
    image: postgres:13-alpine
    restart: always
    environment: 
      POSTGRES_USER: aviasales
      POSTGRES_PASSWORD: aviasales
    volumes: 
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  api:
    build: 
      ./api
    restart: always
    depends_on:
      - db

  app:
    build: 
      ./app
    restart: always
    depends_on:
      - api

  proxy:
    build: 
      ./proxy
    restart: always
    ports: 
      - "8081:80"
    depends_on:
      - app
      - api
